<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('cities')->delete();

        \DB::table('cities')->insert([
            0 =>
            [
                'id' => 1,
                'name' => 'المعادي',
                'description' => 'يشتهر حي المعادي الراقي بشوارعه الهادئة والمشجّرة والمطاعم العصرية. وتنتشر المطاعم الأوروبية والمصرية على طول شارع 9، إلى جانب المقاهي المتخصصة بالمأكولات العضوية والنباتية. وتقدم أماكن الشرب الهادئة التي تشكل الوجهة المفضّلة لدى الحشود الأجنبية مشروبات كوكتيل وتعرض موسيقى حية وألعاب البارات. ويمتد ممشى الكورنيش على طول نهر النيل، الذي يمكن التجول فيه بواسطة الفلوكة، وهي قارب شراعي تقليدي خشبي.',
                'iso' => NULL,
                'state_id' => 1,
                'lat' => '29.9667',
                'lng' => '31.2500',
                'active' => 1,
                'created_at' => '2021-09-13 16:53:13',
                'updated_at' => '2021-09-13 16:53:13',
            ],
            1 =>
            [
                'id' => 2,
                'name' => 'الدقي',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-14 22:08:42',
                'updated_at' => '2021-09-27 23:39:25',
            ],
            2 =>
            [
                'id' => 3,
                'name' => 'مصر الجديدة',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:38:49',
                'updated_at' => '2021-09-27 23:38:49',
            ],
            3 =>
            [
                'id' => 4,
                'name' => 'مدينة نصر',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:39:09',
                'updated_at' => '2021-09-27 23:39:38',
            ],
            4 =>
            [
                'id' => 5,
                'name' => 'التجمع',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:41:04',
                'updated_at' => '2021-09-27 23:41:04',
            ],
            5 =>
            [
                'id' => 6,
                'name' => 'حدائق القبة',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:41:19',
                'updated_at' => '2021-09-27 23:41:19',
            ],
            6 =>
            [
                'id' => 7,
                'name' => 'مدينة العبور',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:41:29',
                'updated_at' => '2021-09-27 23:41:29',
            ],
            7 =>
            [
                'id' => 8,
                'name' => 'المنيل',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:41:40',
                'updated_at' => '2021-09-27 23:41:40',
            ],
            8 =>
            [
                'id' => 9,
                'name' => 'شبرا',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:41:58',
                'updated_at' => '2021-09-27 23:41:58',
            ],
            9 =>
            [
                'id' => 10,
                'name' => 'وسط البلد',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:42:10',
                'updated_at' => '2021-09-27 23:42:10',
            ],
            10 =>
            [
                'id' => 11,
                'name' => 'مدينة السلام',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:42:23',
                'updated_at' => '2021-09-27 23:42:23',
            ],
            11 =>
            [
                'id' => 12,
                'name' => 'الرحاب',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:42:33',
                'updated_at' => '2021-09-27 23:42:33',
            ],
            12 =>
            [
                'id' => 13,
                'name' => 'الزمالك',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:42:42',
                'updated_at' => '2021-09-27 23:42:42',
            ],
            13 =>
            [
                'id' => 14,
                'name' => 'الزيتون',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:42:52',
                'updated_at' => '2021-09-27 23:42:52',
            ],
            14 =>
            [
                'id' => 15,
                'name' => 'السيدة زينب',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:43:07',
                'updated_at' => '2021-09-27 23:43:07',
            ],
            15 =>
            [
                'id' => 16,
                'name' => 'الشروق',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:43:20',
                'updated_at' => '2021-09-27 23:43:20',
            ],
            16 =>
            [
                'id' => 17,
                'name' => 'العاشر من رمضان',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:43:33',
                'updated_at' => '2021-09-27 23:43:33',
            ],
            17 =>
            [
                'id' => 18,
                'name' => 'العباسية',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:43:43',
                'updated_at' => '2021-09-27 23:43:43',
            ],
            18 =>
            [
                'id' => 19,
                'name' => 'المرج',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:43:53',
                'updated_at' => '2021-09-27 23:43:53',
            ],
            19 =>
            [
                'id' => 20,
                'name' => 'المطرية',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:44:06',
                'updated_at' => '2021-09-27 23:44:06',
            ],
            20 =>
            [
                'id' => 21,
                'name' => 'المقطم',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:44:40',
                'updated_at' => '2021-09-27 23:44:40',
            ],
            21 =>
            [
                'id' => 22,
                'name' => 'بولاق',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:44:50',
                'updated_at' => '2021-09-27 23:44:50',
            ],
            22 =>
            [
                'id' => 23,
                'name' => 'حدائق المعادي',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:45:02',
                'updated_at' => '2021-09-27 23:45:02',
            ],
            23 =>
            [
                'id' => 24,
                'name' => 'حدائق حلوان',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:45:10',
                'updated_at' => '2021-09-27 23:45:10',
            ],
            24 =>
            [
                'id' => 25,
                'name' => 'حلوان',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:45:20',
                'updated_at' => '2021-09-27 23:45:20',
            ],
            25 =>
            [
                'id' => 26,
                'name' => 'دار السلام',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:45:32',
                'updated_at' => '2021-09-27 23:45:32',
            ],
            26 =>
            [
                'id' => 27,
                'name' => 'شبرا الخيمة',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:45:47',
                'updated_at' => '2021-09-27 23:45:47',
            ],
            27 =>
            [
                'id' => 28,
                'name' => 'عين شمس',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:45:58',
                'updated_at' => '2021-09-27 23:45:58',
            ],
            28 =>
            [
                'id' => 29,
                'name' => 'مدينة بدر',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:46:11',
                'updated_at' => '2021-09-27 23:46:11',
            ],
            29 =>
            [
                'id' => 30,
                'name' => 'مدينتي',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:46:31',
                'updated_at' => '2021-09-27 23:46:31',
            ],
            30 =>
            [
                'id' => 31,
                'name' => 'مصر القديمة',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 1,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:46:40',
                'updated_at' => '2021-09-27 23:46:40',
            ],
            31 =>
            [
                'id' => 32,
                'name' => 'المهندسين',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:47:24',
                'updated_at' => '2021-09-27 23:47:24',
            ],
            32 =>
            [
                'id' => 33,
                'name' => '٦ أكتوبر',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:47:59',
                'updated_at' => '2021-09-27 23:47:59',
            ],
            33 =>
            [
                'id' => 34,
                'name' => 'الهرم',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:48:12',
                'updated_at' => '2021-09-27 23:48:12',
            ],
            34 =>
            [
                'id' => 35,
                'name' => 'فيصل',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:48:22',
                'updated_at' => '2021-09-27 23:48:22',
            ],
            35 =>
            [
                'id' => 36,
                'name' => 'الشيخ زايد',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:48:57',
                'updated_at' => '2021-09-27 23:48:57',
            ],
            36 =>
            [
                'id' => 37,
                'name' => 'حدائق الاهرام',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:49:11',
                'updated_at' => '2021-09-27 23:49:11',
            ],
            37 =>
            [
                'id' => 38,
                'name' => 'العجوزة',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:49:26',
                'updated_at' => '2021-09-27 23:49:26',
            ],
            38 =>
            [
                'id' => 39,
                'name' => 'الجيزة الجديدة',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:49:45',
                'updated_at' => '2021-09-27 23:52:36',
            ],
            39 =>
            [
                'id' => 40,
                'name' => 'بولاق الدكرور',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:50:00',
                'updated_at' => '2021-09-27 23:50:00',
            ],
            40 =>
            [
                'id' => 41,
                'name' => 'البدراشين',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:50:25',
                'updated_at' => '2021-09-27 23:50:25',
            ],
            41 =>
            [
                'id' => 42,
                'name' => 'الحوامدية',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:50:41',
                'updated_at' => '2021-09-27 23:50:41',
            ],
            42 =>
            [
                'id' => 43,
                'name' => 'العياط',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:51:02',
                'updated_at' => '2021-09-27 23:51:02',
            ],
            43 =>
            [
                'id' => 44,
                'name' => 'ٌإمبابة',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:52:03',
                'updated_at' => '2021-09-27 23:52:03',
            ],
            44 =>
            [
                'id' => 45,
                'name' => 'ميدان الجيزة',
                'description' => NULL,
                'iso' => NULL,
                'state_id' => 2,
                'lat' => NULL,
                'lng' => NULL,
                'active' => 1,
                'created_at' => '2021-09-27 23:52:22',
                'updated_at' => '2021-09-27 23:52:22',
            ],
        ]);


    }
}
